baseURL : https://kolektif.my.id/
title : kolektif.my.id

params:
  description : Dikelola secara kolektif untuk tujuan pengarsipan dan mengabarkan kebaikan

canonifyURLs: true

permalinks:
  posts: /post/:slug/
  pages: /page/:title/
  categories: /kategori/:slug/

markup:
  goldmark:
    renderer:
      unsafe: true

paginate: 5
paginatePath: /