baseURL : https://manzapo.github.io/
title : manzapo.github.io

params:
  description : Dikelola secara kolektif untuk tujuan pengarsipan dan mengabarkan kebaikan

canonifyURLs: true

permalinks:
  posts: /post/:slug/
  pages: /page/:title/
  categories: /kategori/:slug/

markup:
  goldmark:
    renderer:
      unsafe: true

paginate: 5
paginatePath: /